### ISSUE TITLE
Custom video sources

### ISSUE THREAD

**Issue by gegagagua** [flowplayer/flowplayer-quality-selector#17]
Could I add custom video sources, different sources on different qualities?

**Comment by phloxic** [comment]
You mean if the source location doesn't conform to the required filenaming scheme https://flowplayer.org/docs/plugins.html#quality-selector-filenames ?
Well, you could - it just would not work ;-)

The thing is: with a flexible scheme one quickly ends up in an error prone configuration hell - apart from the fact that this would be have to be confined to JavaScript installations only. Something like:

``` js
qualities: [{
  label: "Auto",
  sources: [{ type: "application/x-mpegurl", src: "video.m3u8" }]
}, {
  isDefault: true,
  label: "360p",
  sources: [
     { type: "video/mp4", src: "otherlocation.mp4" },
     { type: "video/flash" src: "mp4:rtmplocation" }
  ]
}, {
  label: "720p",
  sources: [
     { type: "video/mp4", src: "yetanotherlocation.mp4" },
     { type: "video/flash" src: "mp4:anothertmplocation" }
  ]
}]
```

Now imagine that, throw a playlist into the mix, spice up with varying RTMP servers ... Nevermind that it will be somewhat tricky to implement technically, it's very error prone to configure, hard to maintain and debug, not only for the developer, but also for you as a site maintainer.
If this is not just for one video (and its variants) you're arguably better off by adapting your file name layout, especially in the long term - and if it's just for one video, then as well ;-)

That being said: patches are welcome, especially if they do not break other stuff. But it should then really be a general purpose implemenation, somewhat like outlined above.

If we find time we may implement it, but realistically its doubtful. Time is off the essence here, I'm speaking a bit from experience because I offered a such a plugin for Flowplayer v5 for a while, but the interest wasn't exactly overwhelming in relation to the work which has to go into something like that.

**Comment by phloxic** [comment]
Closing in favour of #18
